<a href="https://colab.research.google.com/github/Rozmarynka19/kursAI-sb10/blob/main/2_Biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python --version

Python 3.11.11


In [4]:
!pip freeze | grep numpy

numpy==1.26.4


In [10]:
# wazne - importowanie bibl. numpy
import numpy as np

# tworzenie tablicy
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Array 2x6 - kształt {np.shape(array2x6)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array 2x6 - kształt (2, 6)


In [11]:
# Zadanie: zmień kształt array na (3,4)
array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Array 3x4 - kształt {np.shape(array3x4)}")

Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 3x4 - kształt (3, 4)


In [13]:
# Zadanie: zmień kształt array na (2,2,3)
array2x2x3 = array.reshape(2,2,3)
print(array2x2x3)
print(f"Kształt {np.shape(array2x2x3)}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kształt (2, 2, 3)


In [17]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10])

zagadka = array.reshape(-1,3)
print(zagadka)
print(f"Kształt: {np.shape(zagadka)}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Kształt: (4, 3)


In [19]:
unsorted1D = np.array([3,6,2,4])
print(unsorted1D)
sorted1D = np.sort(unsorted1D)
print(sorted1D)

[3 6 2 4]
[2 3 4 6]


In [22]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)

# TODO: axis=0 - sortowanie po wierszach/kolumnach
sorted2D_axis0 = np.sort(unsorted2D, axis=0)
print(f"Tablica posortowania wzdłuż osi 0:\n{sorted2D_axis0}")

# TODO: axis=1 - sortowanie po wierszach/kolumnach
sorted2D_axis1 = np.sort(unsorted2D, axis=1)
print(f"Tablica posortowania wzdłuż osi 1:\n{sorted2D_axis1}")

[[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowania wzdłuż osi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowania wzdłuż osi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]
