<a href="https://colab.research.google.com/github/Rozmarynka19/kursAI-sb10/blob/main/2_Biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version

Python 3.11.11


In [ ]:
!pip freeze | grep numpy

numpy==1.26.4


In [2]:
# wazne - importowanie bibl. numpy
import numpy as np

# tworzenie tablicy
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)
print(f"Kształt tablicy: {np.shape(array)}")

array2x6 = array.reshape(2,6)
print("Array 2x6")
print(array2x6)
print(f"Array 2x6 - kształt {np.shape(array2x6)}")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Kształt tablicy: (12,)
Array 2x6
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array 2x6 - kształt (2, 6)


In [ ]:
# Zadanie: zmień kształt array na (3,4)
array3x4 = array.reshape(3,4)
print("Array 3x4")
print(array3x4)
print(f"Array 3x4 - kształt {np.shape(array3x4)}")

Array 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 3x4 - kształt (3, 4)


In [ ]:
# Zadanie: zmień kształt array na (2,2,3)
array2x2x3 = array.reshape(2,2,3)
print(array2x2x3)
print(f"Kształt {np.shape(array2x2x3)}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kształt (2, 2, 3)


In [ ]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10])

zagadka = array.reshape(-1,3)
print(zagadka)
print(f"Kształt: {np.shape(zagadka)}")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Kształt: (4, 3)


In [ ]:
unsorted1D = np.array([3,6,2,4])
print(unsorted1D)
sorted1D = np.sort(unsorted1D)
print(sorted1D)

[3 6 2 4]
[2 3 4 6]


In [ ]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
print(unsorted2D)

# TODO: axis=0 - sortowanie po kolumnach
sorted2D_axis0 = np.sort(unsorted2D, axis=0)
print(f"Tablica posortowania wzdłuż osi 0:\n{sorted2D_axis0}")

# TODO: axis=1 - sortowanie po wierszach
sorted2D_axis1 = np.sort(unsorted2D, axis=1)
print(f"Tablica posortowania wzdłuż osi 1:\n{sorted2D_axis1}")

[[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowania wzdłuż osi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowania wzdłuż osi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [6]:
player_data = np.array([
    ("Faker", "T1", 5),
    ("TheSky", "Weibo Gaming", 1),
    ("Uzi", "Emerytowany", 0)
], dtype = [("Nick", "U30"), ("Team", "U30"), ("Worlds Title count", "i4")])

print(player_data)

# sortowanie po kolumnie o nazwie "Team"
print(np.sort(player_data, order="Team"))

[('Faker', 'T1', 5) ('TheSky', 'Weibo Gaming', 1)
 ('Uzi', 'Emerytowany', 0)]
[('Uzi', 'Emerytowany', 0) ('Faker', 'T1', 5)
 ('TheSky', 'Weibo Gaming', 1)]


In [9]:
# random
from numpy import random

# <1, 11) int
for i in range(10):
  print(random.randint(1,11))

# <0,1) float
for i in range(10):
  print(random.rand()*10)

6
3
10
1
3
6
6
6
4
1
0.23193617251651077
0.2599905667366387
0.30806100833966077
0.7769285648828587
0.9412321808833899
0.026856496255810214
0.25822599827590165
0.253927468785886
0.37509381538059317
0.26776079201373604


In [17]:
lista = [1,2,3,4]

print(random.choice(lista, 3))

[1 1 2]


In [27]:
array1D =  np.array([1,2,3,4,5,6,7,8,9])

# elementy do indeksu 4 (włącznie)
print(array1D[:5])

# elementy od indeksu 2 do indeksu 4 (włącznie)
print(array1D[2:5])

# elementy od indeksu 2 do końca
print(array1D[2:])

# elementy od 3 od końca do przedostatniego
print(array1D[-3:-1])

[1 2 3 4 5]
[3 4 5]
[3 4 5 6 7 8 9]
[7 8]


In [36]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

print(array2D[2,1])
print(array2D[:,2:4])
print(array2D[0:2,2:4])

for i in np.nditer(array2D):
  print(i)

12
[[ 3  4]
 [ 8  9]
 [13 14]]
[[3 4]
 [8 9]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [41]:
array2D = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,6]
])

result = np.where(array2D == 6)
print(result)

result = np.where(array2D % 2 == 0, True, False)
print(result)

filtered = array2D[result]
print(filtered)

(array([1, 2]), array([0, 4]))
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True  True]]
[ 2  4  6  8 10 12 14  6]
