<a href="https://colab.research.google.com/github/Rozmarynka19/kursAI-sb10/blob/sr1640/2_Biblioteka_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip freeze | grep numpy

numpy==1.26.4


In [3]:
!python --version

Python 3.11.11


In [5]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"Shape of array: {np.shape(array)}")

Shape of array: (12,)


In [11]:
array2x6 = array.reshape(2,6)
print(f"Array 2x6 = {array2x6}")
print(f"Array 2x6 shape = {np.shape(array2x6)}")

Array 2x6 = [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Array 2x6 shape = (2, 6)


In [12]:
# Kształt na wierszy 3 kolumn 4
array3x4 = array.reshape(3,4)
print(f"Array 3x4 = {array3x4}")
print(f"Array 3x4 shape = {np.shape(array3x4)}")


Array 3x4 = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array 3x4 shape = (3, 4)


In [13]:
# Kształt na 2 tablice po wiersze 2 kolumny 3
array2x2x3 = array.reshape(2,2,3)
print(f"Array 2x2x3 = {array2x2x3}")
print(f"Array 2x2x3 shape = {np.shape(array2x2x3)}")

Array 2x2x3 = [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Array 2x2x3 shape = (2, 2, 3)


In [14]:
zagadka = array.reshape(6,-1)
print(f"zagadka = {zagadka}")
print(f"zagadka shape = {np.shape(zagadka)}")

zagadka = [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
zagadka shape = (6, 2)


In [16]:
unsorted1D = np.array([3,6,2,4])
print(f"Nieposortowana: {unsorted1D}")
print(f"Posortowana: {np.sort(unsorted1D)}")

Nieposortowana: [3 6 2 4]
Posortowana: [2 3 4 6]


In [21]:
unsorted2D = np.array([[7,2,9],
                       [4,8,1],
                       [5,6,3]])
sorted_in_rows = np.sort(unsorted2D, axis=1)
print(sorted_in_rows)

sorted_in_cols = np.sort(unsorted2D, axis=0)
print(sorted_in_cols)

[[2 7 9]
 [1 4 8]
 [3 5 6]]
[[4 2 1]
 [5 6 3]
 [7 8 9]]


In [24]:
players_data = np.array([
    ("Faker", "T1", 5),
    ("TheShy", "Weibo Gaming", 1),
    ("Uzi", "Emerytowany", 0),
], dtype=[
    ("Nick", "U30"),
    ("Team", "U30"),
    ("World Title Count", "i4")
])

print(np.sort(players_data, order="Team"))

[('Uzi', 'Emerytowany', 0) ('Faker', 'T1', 5)
 ('TheShy', 'Weibo Gaming', 1)]


In [26]:
from numpy import random as r

for i in range(10):
  print(r.randint(1,11))

10
5
7
6
10
2
4
7
6
1


In [29]:
for i in range(10):
  print(r.rand()*10+3)

4.232220914969348
6.138698045249795
9.535419265037937
7.809549216008346
5.859313492134488
7.159054446330708
10.523821861637934
10.311358467340927
12.958804952381792
10.794415794413172


In [47]:
lista = [5,2,6,8]
print(f"Losowy element z listy {r.choice(lista, 3)}")

Losowy element z listy [2 2 2]


In [50]:
lista2 = [1,2,3,4,5,6]
r.shuffle(lista2)
print(f"Pomieszana lista: {lista2}")

Pomieszana lista: [6, 4, 5, 2, 1, 3]


In [56]:
array1D = np.array([1,2,3,4,5,6,7,8,9])

print(array1D[2:5]) # od 2 do 4 włącznie (indeksy)
print(array1D[:5]) # od początku do 4 włącznie (indeksy)
print(array1D[3:]) # od indeksu 3
print(array1D[-3:-1]) # elementy od 3 od końca do przedostatniego

[3 4 5]
[1 2 3 4 5]
[4 5 6 7 8 9]
[7 8]


In [65]:
array2D = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15]])
print(array2D[2,1])
print(array2D[:,2:4])
print(array2D[1:3,3:6])
print(array2D[1:,3:])
print(array2D[-2:,-2:])
#[[9,10],
# [14,15]]

12
[[ 3  4]
 [ 8  9]
 [13 14]]
[[ 9 10]
 [14 15]]
[[ 9 10]
 [14 15]]
[[ 9 10]
 [14 15]]


In [64]:
for i in np.nditer(array2D):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [70]:
array2D = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,6]])
mask = np.where(array2D % 2 == 0, True, False)
print(array2D[mask])

[ 2  4  6  8 10 12 14  6]


1.Utwórz 9 elementową tablicę składającą się z losowych liczb z przedziału
<-10;10>.

2.Zmień kształt tablicy na 3x3

3.Posortuj tablicę tak aby wartości były posortowane w kolumnach.

4.Wygeneruj maskę zawierającą wartość True dla wartości nieujemnych i False dla wartości ujemnych.

5.Utwórz tablicę filtered która zawiera tylko nieujemne elementy początkowej tablicy.

Sprawdzić zadanie